[package]
name = "ethertia"
version = "0.1.0"
edition = "2021"
authors = ["dreamtowards"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11"


[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!